name = "passionbots-lms"
compatibility_date = "2025-12-17"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "passionbots-lms-production"
database_id = "425fe9a7-d2d4-4cb5-bc46-090b1981ed8b"
